In [1]:
import torch

torch中的张量和普通的array其实是完全一样的概念，只是进行了新的设定，感觉是皮套人

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

numel是number of elements的缩写，这东西永远是一个标量

In [7]:
x.numel()

12

In [8]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
torch.tensor([[12, 26], [20, 00], [26, 12]])

tensor([[12, 26],
        [20,  0],
        [26, 12]])

上面的这些就是一些常规的操作，其实和numpy基本上就是完全一样的

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

和numpy里面一样，都可以进行一些运算（上面这些），要注意这些运算全部都是按照元素来进行的，并且有小数点才是浮点数，没有小数点会被认为是int

In [18]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [20]:
x = torch.arange(12, dtype=torch.float32).reshape(3, 4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
(torch.cat((x, y), dim=0), torch.cat((x, y), dim=1))

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [21]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
x.sum()

tensor(66.)

torch是基于numpy开发的，所以numpy里面的广播机制也被运用在了numpy里面，要注意这是非常容易出错的一个地方

In [26]:
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [27]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

广播机制其实就是，把更小的那个维度扩充到与更大的一样，上面的例子就是a从31变成32，b从12变成32，这个扩充是通过复制来实现的

python通常不会关注内存的机制，但是一些操作也会导致变量在内存中的储存发生变化

通过原地操作可以解决这个问题

In [28]:
before = id(a)
a = a + b
id(a) == before

False

In [29]:
z = torch.zeros_like(a)
print('id(z):', id(z))
z[:] = a + b
print('id(z):', id(z))

id(z): 140485350532736
id(z): 140485350532736


In [31]:
A = a.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)