其实没啥内容，建议看宋浩老师的课~

In [30]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [31]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [32]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [33]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [34]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [35]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

在数学上我们常常默认矩阵就是一个2d的东西，张量其实就是把2d推广到了nd，可以是任意维度的，但是本质上还是矩阵的组合

In [36]:
X = torch.arange(24).reshape(2, 3, 4)
X
# 234分别是，几个二维矩阵，几个行，几个列，后面更高维度的，以此类推就好

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [37]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法，是矩阵的哈达玛积，其实就是点乘的有意思

这玩意在计算机里面用的更多，但是在数学上，其实可以发现用的不多

In [38]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

求和啥的操作都是很常规的

In [39]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [40]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [41]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [42]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [43]:
A.sum(axis=[0, 1])  # 结果和A.sum()相同

tensor(190.)

求和的时候其实有点像降维操作，虽然实际上仍然可以看作维度不变（只是变成1），但是在计算机里面就会自动的降维

可以设置keepdims来保持维度

In [44]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A
# 可以发现结果是完完全全一样的，但是这里就还是一个51的矩阵，而上面的就是一个长度5的向量

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

保持维度，接下来就可以用广播机制

In [45]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

点乘和点积是不一样的东西！点乘就是按元素相乘，点积是相乘之后求和

所以我们也可以先进行点乘（按元素相乘），然后求和来得到点积（dot）

In [46]:
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [47]:
torch.sum(x * y)

tensor(6.)

要做数学上的矩阵矩阵（向量）乘法，在torch里面必须要用mv或者mm函数来进行

In [48]:
A.shape, x.shape, torch.mv(A, x)
# mv是matrix vector

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [49]:
B = torch.ones(4, 3)
torch.mm(A, B)
# mm是matrix matrix

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

torch里面L1范数和L2具有不一样的定义

L2是norm函数

L1是绝对值求和两个函数

In [50]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [51]:
torch.abs(u).sum()

tensor(7.)

这个是矩阵的F范数，其实也就是矩阵的L2范数......

In [52]:
torch.norm(torch.ones((4, 9)))

tensor(6.)