In [95]:
import torch
import time

In [96]:
# 定义好参数的真实值
true_w = torch.tensor([10.0, -5.0]) # 不加.0会变成int
true_b = 10.06

In [97]:
x = torch.normal(0 ,1, (1000, 2)) # 这个生成数据的方法真的方便
y = torch.matmul(x, true_w) + true_b
y = y + torch.normal(0, 1, y.shape) # 加上噪音

In [98]:
from torch.utils import data

In [99]:
# 向框架里面读入数据
dataset = data.TensorDataset(*(x, y)) # x, y一起输入

In [100]:
# 设置超参数
batch_size = 20
# 迭代对象
data_iter = data.DataLoader(dataset, batch_size, shuffle = True)

In [101]:
next(iter(data_iter)) # 可以发现每次取20个，也就是我们设置好的batch size

[tensor([[ 0.2312, -2.0429],
         [ 0.6349,  1.2550],
         [ 0.0605,  0.5054],
         [ 1.0682, -1.5177],
         [-0.4823, -0.1926],
         [ 0.0352,  0.9522],
         [ 1.3950,  0.5049],
         [-0.9316,  1.1041],
         [-0.9435,  0.5335],
         [ 0.9577,  0.5793],
         [-2.0006, -0.6170],
         [-0.9044,  0.2357],
         [ 0.2108, -0.1710],
         [ 1.8029, -1.5121],
         [ 0.2421, -1.1206],
         [ 0.3719,  0.0709],
         [ 0.0544, -1.9531],
         [ 0.4688, -0.3470],
         [ 0.4639, -0.4959],
         [ 1.1702, -0.5648]]),
 tensor([22.3285,  9.8088,  7.9114, 28.6697,  5.8459,  7.2750, 21.6267, -4.1066,
         -2.2411, 17.1890, -7.2277, -1.1012, 12.5431, 35.3295, 18.3010, 12.5077,
         20.2271, 15.4461, 18.2069, 23.0314])]

In [111]:
from torch import nn # 神经网络模块

In [109]:
# 就是一个最简单的多层感知机（1层），实际上就是线性回归
net = nn.Sequential(
    nn.Linear(2, 1) # input/out 的格式
)

In [104]:
# 进行参数初始化
# 这里可以发现，net对象就是我们所构建的网络
# 0表示第一个网络，因为这里网络只有一层
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [105]:
# 定义损失函数L
# L2的loss torch都直接写好了
loss = nn.MSELoss()

In [106]:
# 接下来就可以开始训练了
# 用了最简单的直接梯度下降法
# 要训练的对象，以及训练率
trainer = torch.optim.SGD(net.parameters(), lr = 0.01)

In [107]:
epoch = 100 # 设置训练的次数

In [108]:
for i in range(epoch):
    for run_x, run_y in data_iter:
        l = loss(net(run_x), run_y) # pytorch 的语法很接近原生Python
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(x), y)
    print(i, l)
    print(net[0].weight.data, net[0].bias.data)

# 可以发现这个训练例子是依托答辩

0 tensor(137.6104, grad_fn=<MseLossBackward0>)
tensor([[ 0.0476, -0.1523]]) tensor([6.0735])
1 tensor(126.4426, grad_fn=<MseLossBackward0>)
tensor([[ 0.3110, -0.1285]]) tensor([8.4376])
2 tensor(125.2037, grad_fn=<MseLossBackward0>)
tensor([[ 0.3422, -0.2340]]) tensor([9.2254])
3 tensor(125.1052, grad_fn=<MseLossBackward0>)
tensor([[ 0.3830, -0.3090]]) tensor([9.5181])
4 tensor(125.0939, grad_fn=<MseLossBackward0>)
tensor([[ 0.4018, -0.2774]]) tensor([9.5565])
5 tensor(125.0548, grad_fn=<MseLossBackward0>)
tensor([[ 0.4122, -0.1872]]) tensor([9.6968])
6 tensor(125.3006, grad_fn=<MseLossBackward0>)
tensor([[ 0.6044, -0.2940]]) tensor([9.6111])
7 tensor(125.2074, grad_fn=<MseLossBackward0>)
tensor([[ 0.5534, -0.2272]]) tensor([9.6264])
8 tensor(125.2048, grad_fn=<MseLossBackward0>)
tensor([[ 0.5055, -0.3024]]) tensor([9.7787])
9 tensor(125.1676, grad_fn=<MseLossBackward0>)
tensor([[ 0.5046, -0.2262]]) tensor([9.7817])
10 tensor(125.2051, grad_fn=<MseLossBackward0>)
tensor([[ 0.5015, -0.3

In [114]:
# 如果是用MLP来构造一个minst的手写数字识别例子
# 其实就是搭积木
net = nn.Sequential(
    nn.Flatten(),  # 首先把输入的矩阵转化为向量，方便后面的感知机隐藏层计算
    nn.Linear(784, 127), 
    nn.ReLU(), # 线性模型用在分类问题中，就是用激活函数来转换，sigmoid函数也是一样的，不过relu最方便
    nn.Linear(127, 10) # 这中间的隐藏层数、节点数是自己随便设置的，所以才会说是个黑箱
)